apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: 100foldtechnologies/planning-app:122dfef4ca192894b2c77fe1344aff7eeceeb5f8
        ports:
        - containerPort: 3000
