apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: 100foldtechnologies/planning-app:9a6646e414530dd505597fd30fbbc95636bb00de
        ports:
        - containerPort: 3000
